### ISSUE TITLE
Enabling trace-agent to start with the regular datadog agent

### ISSUE THREAD

**Issue by donghoang89** [DataDog/datadog-agent-boshrelease#37]
**Steps to reproduce the issue:**
1. Clone DataDog/datadog-agent-boshrelease
2. Run "bosh create-release" to build the boshrelease for datadog-agent
3. Run "bosh upload-release" to push the newly created release to private bosh director
4. Create a bosh manifest to deploy a server with datadog-agent boshrelease

[sample manifest]
---
name: datadog-test

releases:
- name: datadog-agent
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3445.2

instance_groups:
- name: dd-agent
  instances: 1
  jobs:
  - name: dd-agent
    release: datadog-agent
    properties:
      dd:
        use_dogstatsd: yes
        api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        tags: ["datadog", "bosh", "bosh:bosh-exp"]
  vm_type: small
  stemcell: trusty
  persistent_disk: 10240
  networks:
  - name: xxxxxxxxxxxxxxxxxxxxxx
  azs:
  - aws-east-1d

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 1
  serial: false 
[/sample manifest]

5. Run "bosh ssh" to log into the new server
6. Run "monit summary" to verify that datadog-agent boshrelease has been deployed and is running
7. Run "ps -ef | grep dd" to see which datadog process is running

**Describe the results you received:**
[ps  output]
dd-agent/4c499116-f242-49b6-9d75-c9874b700a02:~# ps -ef | grep dd
root         2     0  0 17:27 ?        00:00:00 [kthreadd]
vcap     11184     1  1 17:36 ?        00:00:00 /var/vcap/jobs/dd-agent/packages/dd-agent/bin/agent/agent start -c /var/vcap/jobs/dd-agent/config/ -p /var/vcap/sys/run/dd-agent/agent.pid
root     11456 11433  0 17:37 pts/1    00:00:00 grep --color=auto dd
[/ps output]

**Describe the results you expected:**
[ps output]
dd-agent/4c499116-f242-49b6-9d75-c9874b700a02:~# ps -ef | grep dd
root         2     0  0 17:27 ?        00:00:00 [kthreadd]
root     15733     1  0 17:44 ?        00:00:00 bash /var/vcap/jobs/dd-agent/bin/agent_ctl start
vcap     15765 15733  1 17:44 ?        00:00:00 /var/vcap/jobs/dd-agent/packages/dd-agent/bin/agent/agent start -c /var/vcap/jobs/dd-agent/config/ -p /var/vcap/sys/run/dd-agent/agent.pid
root     15767 15733  0 17:44 ?        00:00:00 /var/vcap/jobs/dd-agent/packages/dd-agent/embedded/bin/trace-agent --config /var/vcap/jobs/dd-agent/config/datadog.yaml --pid /var/vcap/jobs/dd-agent/run/trace-agent.pid
root     16055 15991  0 17:45 pts/1    00:00:00 grep --color=auto dd
[/ps output]

**Additional information you deem important (e.g. issue happens only occasionally):**
The issue is that datadog-agent startup script, agent_ctl, only start the agent binary and not the trace-agent binary.

I have added the trace-agent startup portion and tested the developmental datadog-agent boshrelease on my environment. The trace-agent was able to start and make APM report to datadog server. 

I would like to contribute this change back to datadog-agent boshrelease. My forked repo is at https://github.com/donghoang89/datadog-agent-boshrelease . All the changes can be viewed at https://github.com/donghoang89/datadog-agent-boshrelease/commit/68f7f418dcc4d8b7222b33e2271e49471bed3df4 .

**Comment by donghoang89** [comment]
Sorry for the messed up bosh manifest format above, it was supposed to be

> ---
> name: datadog-test
> 
> releases:
> - name: datadog-agent
>  version: latest
> 
> stemcells:
> - alias: trusty
>   os: ubuntu-trusty
>   version: 3445.2
> 
> instance_groups:
> - name: dd-agent
>   instances: 1
>   jobs:
>   - name: dd-agent
>     release: datadog-agent
>     properties:
>       dd:
>         use_dogstatsd: yes
>         api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>         tags: ["datadog", "bosh", "bosh:bosh-exp"]
>   vm_type: small
>   stemcell: trusty
>   persistent_disk: 10240
>   networks:
>   - name: xxxxxxxxxxxxxxxxxxxxxx
>   azs:
>   - aws-east-1d
> 
> update:
>   canaries: 1
>   canary_watch_time: 30000-180000
>   update_watch_time: 30000-180000
>   max_in_flight: 1
>   serial: false

**Comment by donghoang89** [comment]
Sorry for the messed up bosh manifest format above. It was supposed to be
`---
name: datadog-test

releases:
- name: datadog-agent
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3445.2

instance_groups:
- name: dd-agent
  instances: 1
  jobs:
  - name: dd-agent
    release: datadog-agent
    properties:
      dd:
        use_dogstatsd: yes
        api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        tags: ["datadog", "bosh", "bosh:bosh-exp"]
  vm_type: small
  stemcell: trusty
  persistent_disk: 10240
  networks:
  - name: xxxxxxxxxxxxxxxxxxxxxx
  azs:
  - aws-east-1d

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 1
  serial: false`

**Comment by donghoang89** [comment]
Sorry for the messed up bosh manifest format above. It was supposed to be
---
name: datadog-test

releases:
\- name: datadog-agent
  version: latest

stemcells:
\- alias: trusty
  os: ubuntu-trusty
  version: 3445.2

instance_groups:
\- name: dd-agent
  instances: 1
  jobs:
  \- name: dd-agent
    release: datadog-agent
    properties:
      dd:
        use_dogstatsd: yes
        api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        tags: ["datadog", "bosh", "bosh:bosh-exp"]
  vm_type: small
  stemcell: trusty
  persistent_disk: 10240
  networks:
  \- name: xxxxxxxxxxxxxxxxxxxxxx
  azs:
  \- aws-east-1d

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 1
  serial: false

**Comment by donghoang89** [comment]
Sorry for the messed up bosh manifest format above. It was supposed to be

---
name: datadog-test

releases:
\- name: datadog-agent
\ \ version: latest

stemcells:
\- alias: trusty
\ \ os: ubuntu-trusty
\ \ version: 3445.2

instance_groups:
\- name: dd-agent
\ \ instances: 1
\ \ jobs:
\ \ \- name: dd-agent
\ \ \ \ release: datadog-agent
\ \ \ \ properties:
\ \ \ \ \ \ dd:
\ \ \ \ \ \ \ \ use_dogstatsd: yes
\ \ \ \ \ \ \ \ api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
\ \ \ \ \ \ \ \ tags: ["datadog", "bosh", "bosh:bosh-exp"]
\ \ vm_type: small
\ \ stemcell: trusty
\ \ persistent_disk: 10240
\ \ networks:
\ \ \- name: xxxxxxxxxxxxxxxxxxxxxx
\ \ azs:
\ \ \- aws-east-1d

update:
\ \ canaries: 1
\ \ canary_watch_time: 30000-180000
\ \ update_watch_time: 30000-180000
\ \ max_in_flight: 1
\ \ serial: false

**Comment by donghoang89** [comment]
Sorry for the messed up bosh manifest format above. It was supposed to be

`---
name: datadog-test

releases:
- name: datadog-agent
 version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3445.2

instance_groups:
- name: dd-agent
  instances: 1
  jobs:
  - name: dd-agent
    release: datadog-agent
    properties:
      dd:
        use_dogstatsd: yes
        api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        tags: ["datadog", "bosh", "bosh:bosh-exp"]
  vm_type: small
  stemcell: trusty
  persistent_disk: 10240
  networks:
  - name: xxxxxxxxxxxxxxxxxxxxxx
  azs:
  - aws-east-1d

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 1
  serial: false`

**Comment by donghoang89** [comment]
{noformat}
---
name: datadog-test

releases:
- name: datadog-agent
 version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3445.2

instance_groups:
- name: dd-agent
  instances: 1
  jobs:
  - name: dd-agent
    release: datadog-agent
    properties:
      dd:
        use_dogstatsd: yes
        api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        tags: ["datadog", "bosh", "bosh:bosh-exp"]
  vm_type: small
  stemcell: trusty
  persistent_disk: 10240
  networks:
  - name: xxxxxxxxxxxxxxxxxxxxxx
  azs:
  - aws-east-1d

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 1
  serial: false
{/noformat}

**Comment by donghoang89** [comment]
```
---
name: datadog-test

releases:
- name: datadog-agent
 version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3445.2

instance_groups:
- name: dd-agent
  instances: 1
  jobs:
  - name: dd-agent
    release: datadog-agent
    properties:
      dd:
        use_dogstatsd: yes
        api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        tags: ["datadog", "bosh", "bosh:bosh-exp"]
  vm_type: small
  stemcell: trusty
  persistent_disk: 10240
  networks:
  - name: xxxxxxxxxxxxxxxxxxxxxx
  azs:
  - aws-east-1d

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 1
  serial: false
```

**Comment by donghoang89** [comment]
Sorry for the messed up bosh manifest format above. It was supposed to be

```
---
name: datadog-test

releases:
- name: datadog-agent
 version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: 3445.2

instance_groups:
- name: dd-agent
  instances: 1
  jobs:
  - name: dd-agent
    release: datadog-agent
    properties:
      dd:
        use_dogstatsd: yes
        api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        tags: ["datadog", "bosh", "bosh:bosh-exp"]
  vm_type: small
  stemcell: trusty
  persistent_disk: 10240
  networks:
  - name: xxxxxxxxxxxxxxxxxxxxxx
  azs:
  - aws-east-1d

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 1
  serial: false
```
