### ISSUE TITLE
Forwarder is not enabled

### ISSUE THREAD

**Issue by Manifaust** [DataDog/datadog-agent-boshrelease#44]
I'm a Datadog newbie so please let me know if I'm missing something.

I'm using this Datadog add-on to receive metrics from a Concourse BOSH deployment. Concourse emits metrics to dogstatsd. I can tell by the logs that dogstatsd working and receiving those metrics, but when I look at the Datadog website those metrics don't seem to appear.

After doing some research, it looks like dogstatd sends metrics to the forwarder. But it looks like the forwarder is disabled in [this commit](https://github.com/DataDog/datadog-agent-boshrelease/commit/1a3c331e029bb3b326632fb5a36fa88d4a4d4e65#diff-ee8e8d712201f20946704361cd2f70c7).

Am I right to think that this means emitting to dogstatd will not work using this add-on?

Please let me know if I'm made some bad assumptions, I am trying to learn as much as I could. Here's my add-on and concourse configuration below.

```yaml
# datadog-runtime-config.yaml
releases:
- name: datadog-agent
  version: 2.5.642

addons:
- name: dd-agent
  jobs:
  - name: dd-agent
    release: datadog-agent
  properties:
    dd:
      use_dogstatsd: yes
      api_key: secret
      tags: ["datadog", "bosh", "bosh:bosh-exp"]
      log_level: TRACE

tags:
  owner: datadog
  email: support@datadoghq.com
```

```yaml
# concourse.yml snippet
- release: concourse
  name: atc
  properties:
    datadog:
      agent_host: localhost
      agent_port: 18125
```
